[tool.poetry]
name = "myfm"
version = "0.1.0"
description = ""
authors = ["KM"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
julia = "^0.6.1"
numpy = "^1.26.2"
matplotlib = "^3.8.2"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
install-julia = 'myfm.install_julia:install_julia'
